print('website header')
print('picture update by hasan')
print('add about section')
print('add login button')
print('bugfix login button')
print('change font to cairo')
print('spelling fix')
print('fix spelling part 2')
print('fix bug')
print('add night shift')
print('add night shift2')
print('edit night shift 2')
print('add new variable')
print('change website logo')
print('add hero section')
print('add hero button')
print('change hero font to Montesserat')
print('change hero background')
print('change hero title')
print('add form section')
print('fix form button')
print('update header style')
